### ISSUE TITLE
Detail levels sometimes get messed up (collision instead of visible LOD is shown)

### ISSUE THREAD

**Issue by qoh** [portify/io_scene_dts#16]
Sometimes detail LODs are interpreted as collision and collision LODs are interpreted as detail.

**Comment by qoh** [comment]
![](http://i.imgur.com/cFixhMr.jpg)

**Comment by portify** [comment]
This seems like a somewhat rare issue

**Comment by portify** [comment]
Is this still an issue?

**Comment by qoh** [comment]
I think this still happens. Any .blend samples would be appreciated.

**Comment by qoh** [comment]
I'm going to close this issue until I can find a test case.
