### ISSUE TITLE
Unable to get the addon to work

### ISSUE THREAD

**Issue by leiunn** [portify/io_scene_dts#47]
Hi,

I'm not very experienced with Blender and also not with addons.
I was just looking for a quick and easy way to view .dts files.

Unfortunatly I'm not able to get this addon to work. Maybe I'm just doing something wrong.

I downloaded the zip file from the release tag 0.2.0.

In Blender I went to the Preferences view -> Addons and selected -> Install from file.
Then I selected the .zip file I downloaded and installed it.

Actually Blender says that it installed it and it is also present in the addons folder for blender.

So far, so good.

But I can't find the installed addon in the list of addons and therefor I can not activate it.
I also don't have the import and export options for Torque (.dts).

I tryed this with Blender version 2.81, 2.77 and 2.74 (as mentioned in the __init__.py file).

Can you help me to get this to work? Would really appreciate it.

Thanks and Regards

**Comment by qoh** [comment]
It was last tested with 2.79b, which worked fine; it is expected not to work with 2.80+ as it has not been updated to work with those versions. Try with the latest repository .zip instead of the latest release.

**Comment by leiunn** [comment]
With the .zip from the latest repository it worked and I was able to open the files.

Still the textures and other stuff is not correctly loaded but thats another prblem.

This issue is solved.

Thank you.
